### ISSUE TITLE
Отсев некорректных данных 

### ISSUE THREAD

**Issue by ArtGudvin** [mavrikkk/car_location#1]
Добрый день. Я пользуюсь вашим модулем. Но у меня приходят иногда некорректные данные (старые координаты). Я хотел бы их отсеять. Я пытаюсь их отсеять условием:
`if datetime.now().timestamp() - datetime.strptime(self._last_upd, '%Y-%m-%d %H:%M:%S').timestamp() > 90 : ` (если время пришло старое)

но куда бы я не вставлял эту строку в файле __init__.py, все равно проходят неверные данные.
Подскажите мне!

**Comment by mavrikkk** [comment]
попробуйте после строки
data=json.loads(response.decode('utf8'))

**Comment by ArtGudvin** [comment]
спс, сработало.
Я так понимаю вот эти строки передают данные в базу HA:
                   

>  self._lat = float(data[0]["lat"])
>                     self._lon = float(data[0]["lng"])
>                     self._speed = float(data[0]["speed"])
>                     self._last_upd = data[0]["d"] + ' ' + data[0]["t"]

Интересно, а с помощью применения фильтра к сенсору gps в файле configaration.yaml как то можно отсеять данные?

**Comment by anti-spy** [comment]
> 

Я очень извиняюсь. Не могли бы вы пожалуйста показать как вы вписали фильтр? Как не впишу, у меня ошибку выбивает.

**Comment by mavrikkk** [comment]
я принял пул реквест от @ArtGudvin , так что все уже в модуле )
